export const seedAffiliatePrograms = [
  {
    name: "Razer",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "1-3%",
    cookieDuration: "30 days",
    notes: "A top brand for gaming peripherals.",
  },
  {
    name: "Logitech",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "4-10%",
    cookieDuration: "30 days",
    notes: "Wide range of popular gaming and streaming gear.",
  },
  {
    name: "SteelSeries",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "5-10%",
    cookieDuration: "30 days",
    notes: "Known for high-quality headsets and mice.",
  },
  {
    name: "Corsair",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "5-15%",
    cookieDuration: "30 days",
    notes: "Popular for PC components, peripherals, and streaming gear.",
  },
  {
    name: "Turtle Beach",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "4%",
    cookieDuration: "30 days",
    notes: "A leader in console gaming headsets.",
  },
  {
    name: "Nvidia",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "2-5%",
    cookieDuration: "45 days",
    notes: "The go-to brand for graphics cards.",
  },
  {
    name: "Secret Lab",
    category: "HARDWARE",
    commissionType: "PERCENT",
    commissionRange: "12%",
    cookieDuration: "7 days",
    notes: "The most popular gaming chair brand.",
  },
  {
    name: "Twitch",
    category: "PLATFORMS",
    commissionType: "VARIABLE",
    commissionRange: "5-50%",
    cookieDuration: "N/A",
    notes: "Earn from subscriptions, bits, and game sales.",
  },
  {
    name: "Epic Games",
    category: "PLATFORMS",
    commissionType: "PERCENT",
    commissionRange: "5%",
    cookieDuration: "14 days",
    notes: "Promote games from the Epic Games Store.",
  },
  {
    name: "Zygor Guides",
    category: "PLATFORMS",
    commissionType: "PERCENT",
    commissionRange: "50%",
    cookieDuration: "60 days",
    notes: "High commission for World of Warcraft guides.",
  },
  {
    name: "Big Fish Games",
    category: "PLATFORMS",
    commissionType: "PERCENT",
    commissionRange: "40.6%",
    cookieDuration: "365 days",
    notes: "Promote a wide variety of casual games.",
  },
  {
    name: "Ubisoft",
    category: "PLATFORMS",
    commissionType: "PERCENT",
    commissionRange: "3%",
    cookieDuration: "30 days",
    notes: "Promote popular titles from the Ubisoft store.",
  },
  {
    name: "Nerd or Die",
    category: "STREAMING",
    commissionType: "VARIABLE",
    commissionRange: "10-30%",
    cookieDuration: "Undisclosed",
    notes: "Overlays, alerts, and other stream assets.",
  },
  {
    name: "Into the AM",
    category: "STREAMING",
    commissionType: "PERCENT",
    commissionRange: "10%",
    cookieDuration: "30 days",
    notes: "Popular apparel for gamers and streamers.",
  },
  {
    name: "Loot Crate",
    category: "STREAMING",
    commissionType: "FLAT",
    commissionRange: "$10 per sale",
    cookieDuration: "30 days",
    notes: "Monthly subscription box for gamers.",
  },
  {
    name: "CDKeys",
    category: "MARKETPLACES",
    commissionType: "PERCENT",
    commissionRange: "5%",
    cookieDuration: "30 days",
    notes: "Popular marketplace for discounted game keys.",
  },
  {
    name: "Kinguin",
    category: "MARKETPLACES",
    commissionType: "VARIABLE",
    commissionRange: "Varies",
    cookieDuration: "30 days",
    notes: "Large marketplace for game keys and digital items.",
  },
  {
    name: "Fanatical",
    category: "MARKETPLACES",
    commissionType: "VARIABLE",
    commissionRange: "Varies",
    cookieDuration: "30 days",
    notes: "Bundles and deals on PC games.",
  },
  {
    name: "Green Man Gaming",
    category: "MARKETPLACES",
    commissionType: "VARIABLE",
    commissionRange: "Varies",
    cookieDuration: "30 days",
    notes: "Digital retailer for PC games.",
  },
  {
    name: "Amazon Associates",
    category: "GENERAL",
    commissionType: "PERCENT",
    commissionRange: "3-10%",
    cookieDuration: "24 hours",
    notes: "Promote any product on Amazon, including gaming gear.",
  },
  {
    name: "GamePal",
    category: "GENERAL",
    commissionType: "PERCENT",
    commissionRange: "25%",
    cookieDuration: "80 days",
    notes: "In-game currency and services.",
  },
  {
    name: "Final Mouse",
    category: "GENERAL",
    commissionType: "PERCENT",
    commissionRange: "25%",
    cookieDuration: "30 days",
    notes: "High-end, limited edition gaming mice.",
  },
  {
    name: "ModdedZone",
    category: "GENERAL",
    commissionType: "PERCENT",
    commissionRange: "10%",
    cookieDuration: "90 days",
    notes: "Custom modded controllers.",
  },
];
